name: Run E2E Tests

on: [pull_request]

jobs:
  run-e2e-test:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports: 
          - "5432:5432"
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: apisolid
        # options: >-
        #   --health-cmd="pg_isready -U docker"
        #   --health-interval=10s
        #   --health-timeout=5s
        #   --health-retries=5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - run: pnpm ci
      - run: pnpm test:e2e
        env:
          JWT_SECRET: testing
          DATABASE_URL: "postgres://docker:docker@localhost:5432/apisolid?schame=public"